version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ALLOWED_ORIGINS=http://localhost:3000,https://stock.webtvmedia.net,http://100.107.129.74:3000
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

    depends_on:
      - backend
    restart: always
